# Generated by Django 3.2.4 on 2022-05-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investigator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('investigator_code', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('cases', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reporter_code', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('cases', models.CharField(max_length=5000)),
            ],
        ),
    ]
