# Generated by Django 3.2.4 on 2022-05-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case_code', models.CharField(max_length=11)),
                ('location', models.CharField(max_length=300)),
                ('desc', models.CharField(max_length=5000)),
                ('status', models.CharField(max_length=200)),
                ('reporter_name', models.CharField(max_length=50)),
                ('reporter_phone', models.CharField(max_length=20)),
                ('investigator_code', models.CharField(max_length=11)),
            ],
        ),
    ]
